### ISSUE TITLE
Backend & Frontend Routes

### ISSUE THREAD

**Issue by paulobocanegra** [Shuhei-Shibahara/Sick-Snow#3]
# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain superfluous routes
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by paulobocanegra** [comment]
We just need to update our backend routes for cartItems to snake_case (Rubyland). Everything else looks great!

**Comment by Shuhei-Shibahara** [comment]
Issues have been corrected!

**Comment by paulobocanegra** [comment]
Review the individual routes:

cart_items
GET /api/cartItems - returns items inside of the cart
POST /api/cartItems - adds a item into the cart
DELETE /api/cartItem/:id - deletes a cart item

we need to update those as well

**Comment by Shuhei-Shibahara** [comment]
I have made those updates. Thank You!

**Comment by paulobocanegra** [comment]
Great work! 💯
